dist: trusty
sudo: required
node_js:
  - "8"
language: javascript
install:
  - npm install coveralls
  - npm install codeclimate-test-reporter
  - npm install codacy-coverage
  - npm install mocha-lcov-reporter
  - npm install
script: "npm run test-all; npm run coverage"
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;"
